window.FigmaCopy = {
  "home": [
    "LER CASE COMPLETO",
    "ORBE SOFT",
    "Tecnologia que escala o que a sua empresa já faz bem.",
    "Engenharia de software, inteligência artificial e consultoria estratégica para empresas que precisam crescer com previsibilidade.",
    "AGENDAR DIAGNÓSTICO ESTRATÉGICO",
    "CONHECER O ECOSSISTEMA",
    "Processos validados por gigantes do mercado",
    "SOLUÇÕES",
    "Um ecossistema completo para cada fase do seu crescimento.",
    "Do primeiro MVP à operação industrial em escala — escolha a frente que resolve o seu desafio agora.",
    "Fábrica de Software",
    "Sistemas que não param quando a operação cresce. Arquitetura robusta, código limpo e previsibilidade de entrega para empresas que não podem depender de improviso técnico.",
    "Explorar Solução",
    "Inteligência Artificial",
    "Seus dados já existem. O que falta é inteligência sobre eles. Aplicamos IA para automatizar processos, antecipar falhas e transformar informação dispersa em decisão fundamentada.",
    "Explorar Solução",
    "TechStart",
    "Validação estratégica antes do primeiro real investido em desenvolvimento. Transformamos sua ideia em escopo, roadmap e produto viável — com método, não com palpite.",
    "Explorar Solução",
    "Mobilidade Corporativa",
    "Times conectados, dados centralizados, operação visível em tempo real. Desenvolvemos apps corporativos integrados aos seus sistemas — para o campo, para a gestão e para o cliente final.",
    "Explorar Solução",
    "UX/UI Design",
    "Interface ruim não é problema de estética — é problema de negócio. Projetamos experiências digitais que reduzem fricção, aumentam adoção e fazem o produto entregar o que promete.",
    "Explorar Solução",
    "Indústria 4.0",
    "Chão de fábrica conectado ao sistema de gestão. Monitoramento em tempo real, manutenção preditiva e automação orientada ao processo para operações que não toleram improviso.",
    "Explorar Solução",
    "IT Staff Augmentation",
    "Capacidade técnica qualificada no ritmo do seu projeto. Profissionais alinhados ao seu stack e à sua cultura — sem o custo e o tempo de uma contratação convencional.",
    "Explorar Solução",
    "COMO TRABALHAMOS",
    "Não entregamos apenas software. Entregamos previsibilidade.",
    "Da consultoria inicial à análise de resultados, cada projeto segue um processo estruturado que garante escopo controlado, entregas previsíveis e investimento protegido.",
    "Passo 01 — Consultoria e Diagnóstico",
    "Antes de qualquer linha de código, entendemos o seu negócio. Mapeamos gargalos, validamos premissas e definimos o que realmente precisa ser construído — protegendo seu investimento desde o início.",
    "Passo 02 — Prototipação e Validação",
    "Transformamos o problema em solução tangível antes do desenvolvimento. Protótipos navegáveis, validação com usuários reais e escopo fechado com precisão — para que o que for construído seja o que foi planejado.",
    "Passo 03 — Desenvolvimento e Engenharia",
    "Código limpo, arquitetura escalável e ciclos de entrega transparentes. Você acompanha o progresso, aprova as entregas e mantém total visibilidade sobre o que está sendo construído.",
    "Passo 04 — Qualidade e Mitigação de Risco",
    "Cada entrega passa por validação técnica rigorosa antes de ir para produção. Testes automatizados, revisão de código e processos de QA que eliminam surpresas e protegem a operação.",
    "Passo 05 — Análise de Resultados e Evolução",
    "Não desaparecemos depois da entrega. Acompanhamos os resultados, medimos o impacto e estruturamos a próxima evolução — porque tecnologia não é projeto, é parceria contínua.",
    "RESULTADOS",
    "Evidências de que o método funciona.",
    "Não mostramos telas. Mostramos o que mudou depois que a tecnologia entrou em operação.",
    "INTELIGÊNCIA ARTIFICIAL",
    "Como reduzimos em 40% o tempo de análise operacional com machine learning",
    "LER CASE COMPLETO",
    "VER TODOS OS CASES",
    "Pronto para dar o próximo passo tecnológico da sua empresa?",
    "Se você tem um desafio real — sistema legado travando, produto que não sai do papel, operação que não escala, dados que não viram decisão — podemos começar com um diagnóstico sem compromisso.",
    "FALAR COM UM ESPECIALISTA",
    "Acompanhe nossas redes",
    "Sobre",
    "Home",
    "Quem Somos",
    "Soluções",
    "Cases",
    "Links Rápidos",
    "Contato",
    "Trabalhe Conosco",
    "Termos de Uso",
    "Políticas de Privacidade",
    "Políticas de Cookies",
    "© 2017–2026 - Orbe Soft",
    "Created by",
    "Voltar ao topo",
    "Soluções",
    "Cases",
    "Sobre",
    "PT",
    "Falar com especialista"
  ],
  "about": [
    "Soluções",
    "Cases",
    "Sobre",
    "PT",
    "Falar com especialista",
    "SOBRE A ORBESOFT",
    "A Orbesoft não foi construída para entregar código. Foi construída para ser o parceiro tecnológico que grandes operações precisam quando o crescimento não pode esperar — e o risco não tem margem para erro.",
    "Conheça nossas soluções",
    "Ver cases de sucesso",
    "Processos validados por gigantes do mercado",
    "Trajetória",
    "Uma trajetória medida em resultados, não em promessas.",
    "Nascemos no Brasil com um propósito claro: preencher a lacuna entre o que as grandes indústrias precisavam tecnologicamente e o que o mercado conseguia entregar com maturidade e previsibilidade.",
    "Ao longo dos anos, construímos um ecossistema de soluções — da concepção de produtos digitais à automação industrial — validado por empresas que não aceitam margem para falha: Jeep, Vale, Gerdau, Magneti Marelli e Editora Árvore da Vida.",
    "Nossa atuação ultrapassa fronteiras. Atendemos operações nacionais e internacionais, com equipes capacitadas para trabalhar em português e inglês, integrando times globais sem perder a consistência do processo.",
    "+300 Empresas atendidas",
    "De médias indústrias a grandes corporações como Jeep e Vale",
    "+100 Produtos no mercado",
    "Iniciativas digitais estruturadas, validadas e lançadas com método.",
    "+10M de Usuários ativos",
    "A prova de que tecnologia bem feita é tecnologia que as pessoas adotam.",
    "Nossos pilares",
    "O que nos diferencia não é o que fazemos. É como fazemos.",
    "Transparência",
    "Cada etapa do projeto é documentada, comunicada e validada com o cliente. Não existem surpresas no meio do caminho, existem checkpoints que garantem que estamos no rumo certo.",
    "Previsibilidade",
    "Manifesto",
    "Acreditamos que o maior risco de um projeto de software não é técnico — é a falta de clareza sobre o problema que está sendo resolvido. Por isso, todo projeto começa com diagnóstico, não com código.",
    "Um parceiro tecnológico de verdade não some após o deploy. Ele acompanha os resultados, ajusta a rota e escala junto com a operação do cliente.",
    "É assim que a Orbesoft pensa. É assim que entregamos.",
    "quem confia",
    "Quando a tecnologia impacta o negócio,",
    "a escolha do parceiro importa!",
    "Converse com um de nossos especialistas. Sem script de vendas, apenas um diagnóstico honesto sobre como a tecnologia pode mover a sua operação.",
    "Agendar Diagnóstico Estratégico",
    "Acompanhe nossas redes",
    "Sobre",
    "Home",
    "Quem Somos",
    "Soluções",
    "Cases",
    "Links Rápidos",
    "Contato",
    "Trabalhe Conosco",
    "Termos de Uso",
    "Políticas de Privacidade",
    "Políticas de Cookies",
    "© 2017–2026 - Orbe Soft",
    "Created by",
    "Voltar ao topo"
  ],
  "contact": [
    "Soluções",
    "Cases",
    "Sobre",
    "PT",
    "Falar com especialista",
    "ENTRAR EM CONTATO",
    "o seu desafio.",
    "Preencha os dados e nosso time fará um diagnóstico preliminar da sua operação para entender o cenário atual, identificar o principal gargalo e direcionar a rota tecnológica mais adequada para o seu negócio.",
    "Nome",
    "Seu nome completo",
    "E-mail corporativo",
    "nome@empresa.com.br",
    "WhatsApp",
    "(00) 00000-0000",
    "Empresa",
    "Nome da empresa",
    "Qual o seu principal desafio tecnológico hoje?",
    "Selecione",
    "Solicitar Diagnóstico Estratégico",
    "Um de nossos especialistas fará uma análise prévia do seu contexto e entrará em contato em até 1 dia útil.",
    "Precisa de um contato direto?",
    "Nossa diretoria está à disposição para discutir projetos de alta complexidade técnica e contratos corporativos.",
    "Fale com a nossa equipe",
    "Compartilhe seu contexto, dúvida ou necessidade e nossa equipe direcionará o atendimento da forma mais adequada.",
    "contato@orbesoft.com.br",
    "Prefere uma conversa direta?",
    "Para um contato mais rápido e direto, nossa equipe também está disponível por telefone para orientar você da melhor forma.",
    "+55 48 8823-3780",
    "Acompanhe nossas redes",
    "Sobre",
    "Home",
    "Quem Somos",
    "Soluções",
    "Cases",
    "Links Rápidos",
    "Contato",
    "Trabalhe Conosco",
    "Termos de Uso",
    "Políticas de Privacidade",
    "Políticas de Cookies",
    "© 2017–2026 - Orbe Soft",
    "Created by",
    "Voltar ao topo"
  ],
  "techstart": [
    "LER CASE COMPLETO",
    "Soluções",
    "Cases",
    "Sobre",
    "PT",
    "Falar com especialista",
    "Soluções",
    "TechStart",
    "Techstart",
    "Estruturamos sua iniciativa digital com clareza técnica e validação de mercado, para que cada decisão seja tomada antes de qualquer investimento em desenvolvimento.",
    "Falar com um Especialista",
    "solução Orbe",
    "Consultoria pensada para transformar conceito em produto.",
    "Ideias sem estrutura viram projetos caros. Quando o escopo não está claro, cada nova demanda gera retrabalho, custo extra e decisões tomadas no improviso. A TechStart existe para mudar esse ciclo, entregando o mapa estratégico antes da primeira linha de código.",
    "Validação antes do investimento",
    "Identificamos o real potencial de mercado da sua ideia e eliminamos os riscos antes que eles virem custos.",
    "Escopo com clareza técnica",
    "Definimos funcionalidades, arquitetura e prioridades com precisão — para que o desenvolvimento seja eficiente desde o início.",
    "Roadmap orientado a resultado",
    "Entregamos um plano de execução até o MVP com prazos, requisitos e investimentos mapeados.",
    "PERFIS TECHSTART",
    "Qual é o seu momento?",
    "A consultoria se adapta ao estágio do seu projeto. Escolha o perfil que mais combina com o seu contexto atual.",
    "Início Estratégico",
    "Ideal para empreendedores e intraempreendedores em fase de ideação.",
    "Projeto em Progresso",
    "Ideal para startups e empresas que buscam lançar a primeira versão de um produto com segurança.",
    "Solução Estruturada",
    "Ideal para negócios com um produto já validado ou que necessitam de um plano robusto para crescimento.",
    "Projeto Sob Consulta",
    "Ideal para médias e grandes empresas, projetos de fomento ou soluções de alta complexidade.",
    "Prova social",
    "Estratégia validada por quem já construiu produtos reais.",
    "A TechStart é sustentada pela experiência da Orbe Soft — consultoria que já lançou mais de 100 startups e impactou mais de 10 milhões de usuários. Nossa metodologia foi desenvolvida em projetos reais, com desafios reais. Aqui não tem palpite: tem processo.",
    "VALIDADO POR",
    "Fábrica de software",
    "O TechStart é o começo. A Fábrica é o que vem depois.",
    "A consultoria termina com um produto validado, um roadmap claro e uma arquitetura definida. A partir daí, você tem duas opções: levar esse material para qualquer equipe de desenvolvimento, ou continuar com a Orbesoft.",
    "Quando o cliente escolhe continuar, a Fábrica de Software assume com uma vantagem que nenhuma outra fábrica tem: ela já conhece o produto, o mercado e as decisões de arquitetura tomadas na fase anterior. Sem retrabalho de briefing. Sem curva de aprendizado sobre o negócio.",
    "Conheça a Fábrica de Software",
    "CASES",
    "Histórias de impacto real.",
    "INTELIGÊNCIA ARTIFICIAL",
    "Como reduzimos em 40% o tempo de análise operacional com machine learning",
    "LER CASE COMPLETO",
    "VER TODOS OS CASES",
    "FAQ",
    "Frequentes.",
    "Isso serve para mim, mesmo que eu não entenda de tecnologia?",
    "Sim. A TechStart foi desenhada exatamente para quem tem a visão do negócio, mas não domina o lado técnico. Nossa função é traduzir sua ideia em um plano que qualquer desenvolvedor consiga executar.",
    "Não seria melhor ir direto para o desenvolvimento?",
    "Depende. Se o escopo já está 100% claro, sim. Mas a maioria dos projetos que vai direto para o desenvolvimento acaba reescrevendo tudo depois — porque o produto construído não era o produto necessário. A consultoria existe para evitar esse ciclo caro.",
    "Quanto tempo leva a consultoria?",
    "Varia conforme o perfil do projeto, mas a maioria das entregas acontece entre 2 e 4 semanas — tempo suficiente para estruturar bem, rápido o suficiente para não travar o seu ritmo.",
    "O que acontece depois da consultoria?",
    "Você sai com um documento estratégico completo. A partir daí, pode contratar desenvolvimento com a Orbe Soft ou com qualquer outro parceiro — com a vantagem de ter um briefing técnico que reduz custos e alinhamentos desnecessários.",
    "Pronto para tirar sua ideia do papel com segurança?",
    "Se você tem uma iniciativa digital que precisa de validação, estrutura ou clareza para avançar, podemos desenhar esse caminho com você.",
    "Agendar Diagnóstico Estratégico.",
    "Acompanhe nossas redes",
    "Sobre",
    "Home",
    "Quem Somos",
    "Soluções",
    "Cases",
    "Links Rápidos",
    "Contato",
    "Trabalhe Conosco",
    "Termos de Uso",
    "Políticas de Privacidade",
    "Políticas de Cookies",
    "© 2017–2026 - Orbe Soft",
    "Created by",
    "Voltar ao topo"
  ],
  "solutions": [
    "Soluções",
    "Cases",
    "Sobre",
    "PT",
    "Falar com especialista",
    "Nossas soluções",
    "A Orbesoft reúne sete frentes de engenharia e consultoria para que a sua empresa não precise procurar diferentes fornecedores. Um ecossistema integrado, do primeiro diagnóstico até a inteligência operacional.",
    "Agendar Diagnóstico Estratégico",
    "Introdução",
    "Um ecossistema completo. Uma única parceria.",
    "Cada empresa chega com um gargalo diferente. Identifique a rota que resolve o seu desafio hoje, sabendo que todas elas se conectam quando o seu negócio precisar crescer.",
    "TechStart",
    "Valide sua ideia antes de investir em desenvolvimento.",
    "Diagnóstico estratégico, prototipação e validação de mercado para transformar um conceito em um produto com demanda real — antes de escrever uma única linha de código.",
    "Explorar Solução",
    "Fábrica de Software",
    "Sistemas robustos para operações que não podem parar.",
    "Arquitetura escalável, código limpo e processos de entrega previsíveis para empresas que precisam de tecnologia à altura do seu crescimento.",
    "Explorar Solução",
    "Inteligência Artificial",
    "Transforme dados em decisões. Automatize o que trava sua operação.",
    "Modelos preditivos, automação inteligente e análise de dados para empresas que querem ganhar eficiência sem aumentar custo operacional.",
    "Explorar Solução",
    "Mobilidade Corporativa",
    "Coloque a sua operação na palma da mão da sua equipe.",
    "Aplicativos nativos e híbridos de alta performance para força de vendas, logística, equipes de campo ou produto B2C — integrados ao seu back-end com segurança de dados corporativos.",
    "Explorar Solução",
    "UX/UI Design",
    "Interfaces que sua equipe usa — e o seu cliente não abandona.",
    "Design centrado no usuário, testes de usabilidade e redução de carga cognitiva para sistemas que precisam ser adotados, não tolerados.",
    "Explorar Solução",
    "Indústria 4.0",
    "Integre o chão de fábrica ao software corporativo em tempo real.",
    "IoT, automação de processos industriais e realidade aumentada para operações que exigem sincronização entre maquinário, dado e decisão — com foco em segurança e eficiência.",
    "Explorar Solução",
    "IT Staff Augmentation",
    "Expanda sua capacidade técnica sem perder o controle do projeto.",
    "Squads sêniores integrados à sua equipe, com a governança e a maturidade de um parceiro tecnológico — não a dependência de um fornecedor de hora técnica.",
    "Explorar Solução",
    "CONEXÃO",
    "Nenhuma rota é um beco sem saída.",
    "As soluções da Orbesoft foram desenhadas para se complementar. O MVP validado pelo TechStart escala pela Fábrica de Software. A Fábrica alimenta a IA. A IA guia a Indústria 4.0. Você escolhe onde entrar. A parceria define onde chegar.",
    "A rota certa começa pelo seu cenário.",
    "Mapeamos o seu cenário e indicamos qual combinação de soluções gera o maior retorno para a sua operação.",
    "Fale com um Especialista",
    "Acompanhe nossas redes",
    "Sobre",
    "Home",
    "Quem Somos",
    "Soluções",
    "Cases",
    "Links Rápidos",
    "Contato",
    "Trabalhe Conosco",
    "Termos de Uso",
    "Políticas de Privacidade",
    "Políticas de Cookies",
    "© 2017–2026 - Orbe Soft",
    "Created by",
    "Voltar ao topo"
  ],
  "factory": [
    "LER CASE COMPLETO",
    "Arquiteturas escaláveis",
    "Estruturamos soluções preparadas para acompanhar o crescimento da empresa sem criar gargalos futuros.",
    "Soluções",
    "Cases",
    "Sobre",
    "PT",
    "Falar com especialista",
    "Soluções",
    "Fábrica de Software",
    "FÁBRICA DE SOFTWARE",
    "Falar com um Especialista",
    "solução Orbe",
    "Engenharia pensada para sustentar crescimento.",
    "Sistemas engessados travam processos, aumentam o retrabalho e dificultam o crescimento da operação. Quando a estrutura não acompanha o negócio, cada nova demanda passa a representar mais risco, mais custo e menos previsibilidade.",
    "Evolução com mais previsibilidade",
    "Conduzimos a entrega com método e visão de longo prazo para que a tecnologia sustente o crescimento com mais segurança.",
    "Integração entre sistemas e operações",
    "Conectamos fluxos, dados e áreas críticas para reduzir ruído operacional e dar mais continuidade à operação.",
    "PARA QUEM É",
    "A Fábrica de Software é para quem não pode depender de improvisação.",
    "Se algum dos cenários abaixo descreve sua realidade, é provável que sua operação precise de uma estrutura de desenvolvimento mais sólida.",
    "Seu sistema atual trava ou falha com frequência em picos de uso",
    "Sua equipe de TI passa mais tempo apagando incêndio do que evoluindo o produto",
    "Cada nova funcionalidade demora mais do que deveria e gera bugs em outras partes",
    "A integração entre sistemas é feita manualmente ou por gambiarras técnicas",
    "Você depende de um único desenvolvedor ou fornecedor para manter tudo funcionando",
    "Você sente que o sistema não vai aguentar o crescimento que está planejando",
    "Prova social",
    "Processos validados por gigantes do mercado.",
    "Empresas como Jeep, Vale, Gerdau e Magneti Marelli sustentam o argumento desta página: nossa engenharia foi validada em contextos exigentes, onde estabilidade, previsibilidade e maturidade são pré-requisitos. Os marcos orientam usar a prova social enterprise para quebrar o medo de amadorismo e reforçar confiança nas páginas de serviço.",
    "VALIDADO POR",
    "CASES",
    "Histórias de impacto real.",
    "INTELIGÊNCIA ARTIFICIAL",
    "Como reduzimos em 40% o tempo de análise operacional com machine learning",
    "LER CASE COMPLETO",
    "VER TODOS OS CASES",
    "Ainda na fase de ideia?",
    "Comece pelo TechStart.",
    "Conheça a techstart",
    "A Fábrica executa com mais velocidade e menos risco quando o produto já passou por validação de mercado e prototipação.",
    "Se a sua iniciativa ainda está no papel, o TechStart estrutura o caminho antes de qualquer linha de código.",
    "Pronto para escalar a sua operação com segurança?",
    "Se a sua empresa precisa modernizar sistemas, sustentar crescimento com mais segurança ou substituir estruturas que já não acompanham a operação, nós podemos desenhar essa evolução com clareza e previsibilidade.",
    "Agendar Diagnóstico Estratégico.",
    "Acompanhe nossas redes",
    "Sobre",
    "Home",
    "Quem Somos",
    "Soluções",
    "Cases",
    "Links Rápidos",
    "Contato",
    "Trabalhe Conosco",
    "Termos de Uso",
    "Políticas de Privacidade",
    "Políticas de Cookies",
    "© 2017–2026 - Orbe Soft",
    "Created by",
    "Voltar ao topo"
  ],
  "ai": [
    "LER CASE COMPLETO",
    "Soluções",
    "Cases",
    "Sobre",
    "PT",
    "Falar com especialista",
    "Soluções",
    "Inteligência Artifical",
    "INTELIGÊNCIA ARTIFICIAL",
    "Aplicamos Inteligência Artificial para transformar dados dispersos em eficiência operacional, automação de processos e inteligência de negócio, de forma estruturada e com impacto mensurável.",
    "Falar com um Especialista",
    "solução Orbe",
    "IA aplicada para sustentar operação e crescimento.",
    "A maioria das empresas já tem os dados. O problema é que eles ficam presos em sistemas isolados, planilhas e processos manuais. Quando a IA não está integrada à operação, a empresa perde tempo, repete erros e toma decisões com informação atrasada. Nós mudamos isso.",
    "Automação de processos críticos",
    "Eliminamos tarefas repetitivas e propensas a erro, liberando sua equipe para o que realmente importa.",
    "Modelos orientados ao seu negócio",
    "Não aplicamos IA genérica. Desenvolvemos soluções treinadas para o contexto e os dados da sua operação.",
    "Inteligência operacional em tempo real",
    "Painéis, alertas e predições que transformam dados em decisões rápidas e fundamentadas.",
    "ONDE A IA GERA IMPACTO",
    "IA que resolve problemas reais, não apenas impressiona.",
    "Cada setor tem desafios específicos. Veja onde aplicamos inteligência artificial com resultado mensurável:",
    "Indústria e Manufatura",
    "Manutenção preditiva, controle de qualidade automatizado, previsão de demanda e otimização de linha de produção.",
    "Varejo e E-commerce",
    "Personalização de experiência, precificação dinâmica, previsão de estoque e análise de comportamento de compra.",
    "Saúde e Clínicas",
    "Triagem inteligente, apoio a diagnóstico, gestão de agenda e análise de prontuários para identificar padrões clínicos.",
    "Financeiro e Seguros",
    "Detecção de fraude em tempo real, análise de crédito, automação de processos regulatórios e relatórios preditivos.",
    "Logística e Distribuição",
    "Otimização de rotas, previsão de atrasos, gestão de frota e rastreamento inteligente de entregas.",
    "Serviços e Operações Internas",
    "Automação de atendimento, classificação de tickets, geração de relatórios e apoio à tomada de decisão gerencial.",
    "Prova social",
    "IA que gera resultado, não só impressão.",
    "Muito se fala em Inteligência Artificial. Poucos entregam algo que funciona dentro da realidade de uma operação. Na Orbe Soft, IA não é tendência — é ferramenta. Aplicamos onde há problema real, com estrutura para sustentar o resultado ao longo do tempo.",
    "VALIDADO POR",
    "CASES",
    "Histórias de impacto real.",
    "INTELIGÊNCIA ARTIFICIAL",
    "Como reduzimos em 40% o tempo de análise operacional com machine learning",
    "LER CASE COMPLETO",
    "VER TODOS OS CASES",
    "DESMISTIFICANDO A IA",
    "Perguntas que todo gestor faz antes de decidir.",
    "Precisamos ter um time de dados para começar?",
    "Não necessariamente. Trabalhamos com o que sua empresa já tem. O primeiro passo é um diagnóstico para entender quais dados existem e quais problemas eles podem resolver.",
    "IA não é coisa para grandes empresas?",
    "Essa percepção está mudando rápido. Hoje, médias empresas são as que mais ganham com IA — porque os ganhos de eficiência têm impacto proporcional maior do que em corporações com estruturas já consolidadas.",
    "Quanto tempo leva para ver resultado?",
    "Depende da complexidade. Automações simples de processo podem gerar resultado em semanas. Modelos preditivos mais robustos geralmente levam de 2 a 4 meses para entrar em operação estável.",
    "E se o modelo errar?",
    "Todo modelo tem margem de erro — e isso é considerado no projeto. Entregamos soluções com camadas de validação, monitoramento contínuo e ajuste ao longo do tempo. IA bem feita melhora com uso.",
    "Pronto para usar os dados da sua empresa a favor da operação?",
    "Se sua empresa tem dados e ainda toma decisões no improviso, podemos mostrar onde a IA pode gerar impacto real — sem complexidade desnecessária.",
    "Agendar Diagnóstico Estratégico.",
    "Acompanhe nossas redes",
    "Sobre",
    "Home",
    "Quem Somos",
    "Soluções",
    "Cases",
    "Links Rápidos",
    "Contato",
    "Trabalhe Conosco",
    "Termos de Uso",
    "Políticas de Privacidade",
    "Políticas de Cookies",
    "© 2017–2026 - Orbe Soft",
    "Created by",
    "Voltar ao topo"
  ],
  "mobile": [
    "LER CASE COMPLETO",
    "Soluções",
    "Cases",
    "Sobre",
    "PT",
    "Falar com especialista",
    "Soluções",
    "Mobilidade Corporativa",
    "MOBILIDADE CORPORATIVA",
    "Desenvolvemos experiências mobile que conectam equipes, dados e decisões, com agilidade, segurança e integração real aos sistemas da sua empresa.",
    "Falar com um Especialista",
    "solução Orbe",
    "Mobile pensado para a realidade da sua operação.",
    "Apps genéricos não resolvem problemas específicos. Quando o mobile não está integrado aos processos da empresa, ele se torna mais uma ferramenta paralela, e o time acaba trabalhando em torno dele, não com ele. Nós desenvolvemos soluções que se encaixam onde a operação realmente acontece.",
    "Integração com sistemas existentes",
    "Conectamos o app aos seus ERPs, CRMs e fontes de dados para eliminar retrabalho e manter a informação centralizada.",
    "Experiência funcional e fluida",
    "Interfaces que o time adota de verdade — porque foram pensadas para o fluxo de trabalho real, não para uma demo.",
    "Segurança e controle corporativo",
    "Gestão de acessos, permissões e dados sensíveis com os padrões exigidos por operações de médio e grande porte.",
    "O QUE DESENVOLVEMOS",
    "Soluções mobile para os contextos mais exigentes.",
    "Não existe um único tipo de app corporativo. Desenvolvemos conforme o desafio — seja para times em campo, gestão interna ou experiência do cliente final.",
    "Apps de Força de Vendas",
    "Catálogo de produtos, pedidos offline, histórico de clientes e metas em tempo real para representantes e vendedores externos.",
    "Apps de Gestão de Campo",
    "Ordens de serviço, checklist de inspeção, registro de ocorrências e coleta de dados técnicos com ou sem conexão à internet.",
    "Dashboards Executivos Mobile",
    "Indicadores de negócio em tempo real, alertas críticos e acesso a relatórios para tomada de decisão em qualquer lugar.",
    "Apps de Integração Operacional",
    "Soluções que conectam colaboradores, aprovações, workflows e dados entre setores — eliminando e-mail e WhatsApp como ferramentas de processo.",
    "Apps B2C com Lógica Corporativa",
    "Experiências mobile para o cliente final com arquitetura enterprise por trás — segurança, escalabilidade e integração com os sistemas da empresa.",
    "APP PRÓPRIO VS. SOLUÇÃO GENÉRICA",
    "Por que uma solução sob medida entrega mais do que uma plataforma pronta.",
    "Integração com seus sistemas",
    "Personalização de fluxo",
    "Custo ao longo do tempo",
    "Adoção pelo time",
    "Escalabilidade",
    "Plataforma genérica",
    "Parcial ou via conectores caros",
    "Limitada pelo produto",
    "Cresce com usuários/módulos",
    "Depende de adaptação da equipe",
    "Depende do fornecedor",
    "Solução Orbe",
    "Nativa, construída para o seu stack",
    "Total, orientada ao seu processo",
    "Previsível e sem depender de licença",
    "Desenhada para o fluxo real de uso",
    "Controlada por você",
    "Plataformas genéricas resolvem casos genéricos. Se sua operação tem especificidades, uma solução própria paga o investimento rapidamente.",
    "Prova social",
    "Mobile que trabalha pela empresa, não contra ela.",
    "Mobilidade corporativa não é sobre ter um app bonito. É sobre garantir que a informação certa chegue à pessoa certa, no momento certo, independente de onde ela esteja. É isso que entregamos — com arquitetura robusta e integração que sustenta o crescimento.",
    "VALIDADO POR",
    "CASES",
    "Histórias de impacto real.",
    "INTELIGÊNCIA ARTIFICIAL",
    "Como reduzimos em 40% o tempo de análise operacional com machine learning",
    "LER CASE COMPLETO",
    "VER TODOS OS CASES",
    "Pronto para levar sua operação para o mobile com segurança?",
    "Se sua empresa precisa conectar times, agilizar processos ou substituir soluções improvisadas, podemos desenhar o caminho certo.",
    "Agendar Diagnóstico Estratégico.",
    "Acompanhe nossas redes",
    "Sobre",
    "Home",
    "Quem Somos",
    "Soluções",
    "Cases",
    "Links Rápidos",
    "Contato",
    "Trabalhe Conosco",
    "Termos de Uso",
    "Políticas de Privacidade",
    "Políticas de Cookies",
    "© 2017–2026 - Orbe Soft",
    "Created by",
    "Voltar ao topo"
  ],
  "ux": [
    "LER CASE COMPLETO",
    "Soluções",
    "Cases",
    "Sobre",
    "PT",
    "Falar com especialista",
    "Soluções",
    "UX/UI Design",
    "UX/UI DESIGN",
    "Criamos experiências digitais claras, funcionais e orientadas ao usuário — para reduzir fricção, aumentar adoção e garantir que o produto entregue o que promete.",
    "Falar com um Especialista",
    "solução Orbe",
    "Design pensado para gerar resultado, não só aprovação.",
    "Um produto com design ruim não falha porque é feio. Falha porque confunde, frustra e faz o usuário desistir. Quando a experiência não está alinhada ao comportamento real de quem usa, a empresa perde conversão, aumenta suporte e compromete a percepção de valor. Design bem feito é investimento, não custo.",
    "Pesquisa e arquitetura de informação",
    "Conectamos o app aos seus ERPs, CRMs e fontes de dados para eliminar retrabalho e manter a informação centralizada.",
    "Interfaces que reduzem fricção",
    "Interfaces que o time adota de verdade — porque foram pensadas para o fluxo de trabalho real, não para uma demo.",
    "Design system escalável",
    "Componentes consistentes e documentados que aceleram o desenvolvimento e mantêm a identidade do produto ao longo do tempo.",
    "NOSSO PROCESSO",
    "Design que começa com perguntas, não com telas.",
    "Cada projeto de UX/UI passa por um processo estruturado — porque boas interfaces não nascem do gosto de ninguém, mas da compreensão de como as pessoas realmente se comportam.",
    "01",
    "Descoberta e Pesquisa",
    "Entrevistas com usuários, análise de comportamento, benchmarks de mercado e mapeamento das dores mais críticas na jornada atual.",
    "02",
    "Arquitetura de Informação",
    "Definição da estrutura de navegação, hierarquia de conteúdo e fluxos principais — antes de qualquer decisão visual.",
    "03",
    "Wireframes e Protótipo",
    "Estruturação das telas em baixa e média fidelidade para validar os fluxos com stakeholders e usuários reais antes de entrar no visual.",
    "04",
    "Design Visual e UI",
    "Aplicação da identidade visual, tipografia, cores, componentes e micro-interações — com foco em clareza, consistência e beleza funcional.",
    "05",
    "Design System e Handoff",
    "Documentação de componentes, tokens de design e especificações técnicas para que o desenvolvimento implemente com fidelidade e o produto escale com consistência.",
    "O QUE ENTREGAMOS",
    "Entregáveis concretos, não apenas telas bonitas.",
    "Ao final de um projeto de UX/UI com a Orbe Soft, você recebe ativos que têm uso imediato — tanto para o desenvolvimento quanto para a evolução contínua do produto.",
    "Mapa de jornada do usuário",
    "Arquitetura de informação e sitemap",
    "Wireframes de todos os fluxos principais",
    "Protótipo navegável para validação",
    "Telas em alta fidelidade (desktop e mobile)",
    "Design system com componentes documentados",
    "Handoff técnico para desenvolvimento",
    "Relatório de pesquisa com usuários",
    "Prova social",
    "Clareza é a melhor funcionalidade que um produto pode ter.",
    "Na Orbe Soft, design não é etapa final. É ponto de partida. Toda solução começa pela jornada do usuário — porque entender como as pessoas interagem com o produto é o que define se ele vai crescer ou ser abandonado. Aqui, beleza e função andam juntas, sempre.",
    "VALIDADO POR",
    "CASES",
    "Histórias de impacto real.",
    "INTELIGÊNCIA ARTIFICIAL",
    "Como reduzimos em 40% o tempo de análise operacional com machine learning",
    "LER CASE COMPLETO",
    "VER TODOS OS CASES",
    "Pronto para transformar a experiência do seu produto digital?",
    "Se seus usuários estão travando, saindo ou não adotando o produto como esperado, podemos identificar onde está o problema e redesenhar com clareza.",
    "Agendar Diagnóstico Estratégico.",
    "Acompanhe nossas redes",
    "Sobre",
    "Home",
    "Quem Somos",
    "Soluções",
    "Cases",
    "Links Rápidos",
    "Contato",
    "Trabalhe Conosco",
    "Termos de Uso",
    "Políticas de Privacidade",
    "Políticas de Cookies",
    "© 2017–2026 - Orbe Soft",
    "Created by",
    "Voltar ao topo"
  ],
  "industry": [
    "LER CASE COMPLETO",
    "Soluções",
    "Cases",
    "Sobre",
    "PT",
    "Falar com especialista",
    "Soluções",
    "Industria 4.0",
    "INDÚSTRIA 4.0",
    "Conectamos máquinas, sistemas e pessoas para ampliar a eficiência, reduzir falhas e dar à sua operação a previsibilidade que o crescimento exige.",
    "Falar com um Especialista",
    "solução Orbe",
    "Tecnologia industrial pensada para quem não pode parar.",
    "Operações industriais não toleram improviso. Quando os sistemas não se comunicam, quando os dados chegam tarde e quando as decisões dependem de planilhas manuais, o custo operacional sobe e a margem encolhe. A integração entre tecnologia e operação não é mais diferencial, é pré-requisito para competir.",
    "Integração entre máquinas e sistemas",
    "Conectamos equipamentos, sensores e softwares para que os dados fluam em tempo real — do chão de fábrica à gestão.",
    "Monitoramento e rastreabilidade",
    "Visibilidade completa da operação com dashboards, alertas e histórico de desempenho para antecipar falhas e reduzir perdas.",
    "Automação orientada ao processo",
    "Eliminamos etapas manuais críticas e reduzimos variabilidade — para que a operação escale sem depender de volume humano.",
    "SINAIS DE ALERTA",
    "Sua operação está pedindo por mais tecnologia?",
    "Alguns sintomas aparecem antes da empresa reconhecer que o problema é estrutural. Veja se algum desses cenários é familiar:",
    "Você ainda recebe dados de produção via planilha ou e-mail",
    "Uma falha em um equipamento para toda a linha — e você descobre tarde demais",
    "Seus sistemas de gestão e operação não se comunicam",
    "As decisões de compra de insumos dependem de estimativa, não de dado",
    "Você não consegue rastrear a origem de uma não conformidade com agilidade",
    "A variabilidade na produção é alta e a causa raramente é identificada de forma precisa",
    "CONEXÃO COM O ECOSSISTEMA",
    "Indústria 4.0 funciona melhor quando conectada às outras frentes.",
    "A transformação digital industrial raramente acontece em uma única frente. Veja como a solução de Indústria 4.0 se conecta ao ecossistema Orbe Soft:",
    "+ Fábrica de Software",
    "Os sistemas que gerenciam sua operação industrial precisam de arquitetura robusta para suportar volume, integrações e crescimento sem travar.",
    "+ Inteligência Artificial",
    "Os dados coletados no chão de fábrica são a matéria-prima para modelos preditivos, detecção de anomalias e otimização contínua de processo.",
    "+ Mobilidade Corporativa",
    "Times em campo precisam de acesso mobile às informações da operação — ordens de serviço, checklists, alertas e registros em tempo real.",
    "+ UX/UI Design",
    "Painéis e interfaces operacionais mal projetados geram erros humanos. Design bem feito aumenta adesão e reduz falhas de uso.",
    "Prova social",
    "Indústria 4.0 na prática, não no discurso.",
    "Muito se fala em transformação digital industrial. Pouco se entrega com consistência. Na Orbe Soft, trabalhamos com a realidade de cada operação — respeitando o que funciona, integrando o que falta e construindo a evolução sem parar a produção. Tecnologia robusta para operações que não podem errar.",
    "VALIDADO POR",
    "CASES",
    "Histórias de impacto real.",
    "INTELIGÊNCIA ARTIFICIAL",
    "Como reduzimos em 40% o tempo de análise operacional com machine learning",
    "LER CASE COMPLETO",
    "VER TODOS OS CASES",
    "Pronto para dar mais controle e previsibilidade à sua operação industrial?",
    "Se sua operação ainda depende de processos manuais, dados fragmentados ou sistemas que não se comunicam, podemos estruturar a evolução com segurança.",
    "Agendar Diagnóstico Estratégico.",
    "Acompanhe nossas redes",
    "Sobre",
    "Home",
    "Quem Somos",
    "Soluções",
    "Cases",
    "Links Rápidos",
    "Contato",
    "Trabalhe Conosco",
    "Termos de Uso",
    "Políticas de Privacidade",
    "Políticas de Cookies",
    "© 2017–2026 - Orbe Soft",
    "Created by",
    "Voltar ao topo"
  ],
  "staff": [
    "LER CASE COMPLETO",
    "Soluções",
    "Cases",
    "Sobre",
    "PT",
    "Falar com especialista",
    "Soluções",
    "It Staff Augmentation",
    "IT STAFF AUGMENTATION",
    "Expandimos sua equipe com profissionais de tecnologia alinhados ao ritmo, à cultura e aos desafios da sua operação, sem o custo e o tempo de uma contratação convencional.",
    "Falar com um Especialista",
    "solução Orbe",
    "Expansão técnica que acompanha o negócio.",
    "Contratar bem leva tempo. E quando o projeto não pode esperar, a operação fica refém da agenda do RH. Profissionais desalinhados ao contexto geram retrabalho, fricção e atraso. Staff Augmentation resolve isso: você ganha capacidade técnica qualificada, integrada ao seu time, sem abrir mão do controle do projeto.",
    "Profissionais alinhados ao seu stack",
    "Selecionamos especialistas com experiência nas tecnologias e metodologias que sua operação já usa — sem curva de aprendizado desnecessária.",
    "Integração real ao time",
    "Não enviamos terceiros desconectados. Os profissionais operam dentro do seu processo, nos seus rituais, com visibilidade total da sua liderança.",
    "Escala no ritmo do projeto",
    "Aumente ou reduza a equipe conforme a demanda — com agilidade e sem os encargos de uma contratação permanente.",
    "STAFF AUGMENTATION VS. OUTRAS OPÇÕES",
    "Por que empresas escolhem este modelo?",
    "Cada modelo de contratação técnica tem seu lugar. Staff Augmentation se destaca quando velocidade, flexibilidade e qualidade precisam coexistir.",
    "Velocidade de início",
    "Controle do trabalho",
    "Alinhamento ao contexto",
    "Escalabilidade",
    "Custo em projetos pontuais",
    "Continuidade e gestão",
    "CLT",
    "Lenta",
    "Total",
    "Alto, mas demora",
    "Burocrática",
    "Alto",
    "Interna",
    "Freelancer",
    "Rápida, mas incerta",
    "Total",
    "Variável",
    "Limitada",
    "Baixo-médio",
    "Sua responsabilidade",
    "Staff Augmentation",
    "Rápida e estruturada",
    "Total",
    "Alto desde o início",
    "Flexível",
    "Previsível e justo",
    "Compartilhada com a Orbe",
    "COMO FUNCIONA A ALOCAÇÃO",
    "Do briefing ao primeiro dia de trabalho em menos de duas semanas.",
    "Nosso processo de alocação foi desenhado para ser rápido sem ser impreciso — porque profissional errado custa mais do que vaga aberta.",
    "01",
    "Briefing Técnico",
    "Entendemos o projeto, o stack, a metodologia do time e o perfil comportamental necessário. Não alocamos sem contexto.",
    "02",
    "Seleção e Curadoria",
    "Mapeamos os profissionais disponíveis na nossa rede e selecionamos os que têm fit técnico e de cultura com o seu time.",
    "03",
    "Apresentação de Perfis",
    "Você recebe os perfis selecionados com histórico, stack, projetos anteriores e nossa avaliação técnica. Você decide quem entrevistar.",
    "04",
    "Entrevista e Validação",
    "Você faz a entrevista final. Aprovado o perfil, cuidamos de toda a parte contratual e operacional.",
    "05",
    "Onboarding e Integração",
    "O profissional entra no seu time com contexto — não jogamos ninguém no projeto sem alinhamento prévio.",
    "06",
    "Acompanhamento Contínuo",
    "Durante toda a alocação, a Orbe Soft acompanha a performance e a integração — e age rapidamente se algo precisar ser ajustado.",
    "Prova social",
    "Velocidade sem abrir mão da qualidade técnica.",
    "Na Orbe Soft, não fornecemos mão de obra. Entregamos capacidade técnica com contexto. Cada profissional alocado passou por um processo rigoroso de avaliação e é acompanhado ao longo do projeto. Porque time bom não é o maior — é o mais alinhado.",
    "VALIDADO POR",
    "CASES",
    "Histórias de impacto real.",
    "INTELIGÊNCIA ARTIFICIAL",
    "Como reduzimos em 40% o tempo de análise operacional com machine learning",
    "LER CASE COMPLETO",
    "VER TODOS OS CASES",
    "Pronto para escalar sua equipe técnica com segurança?",
    "Se seu time precisa de reforço para entregar mais rápido, cobrir uma demanda específica ou sustentar um crescimento inesperado, podemos montar a estrutura certa.",
    "Agendar Diagnóstico Estratégico.",
    "Acompanhe nossas redes",
    "Sobre",
    "Home",
    "Quem Somos",
    "Soluções",
    "Cases",
    "Links Rápidos",
    "Contato",
    "Trabalhe Conosco",
    "Termos de Uso",
    "Políticas de Privacidade",
    "Políticas de Cookies",
    "© 2017–2026 - Orbe Soft",
    "Created by",
    "Voltar ao topo"
  ],
  "caseDetail": [
    "LER CASE COMPLETO",
    "Soluções",
    "Cases",
    "Sobre",
    "PT",
    "Falar com especialista",
    "Cases",
    "Segmento",
    "Como reduzimos em 40% o tempo de análise operacional com IA",
    "INTELIGÊNCIA ARTIFICIAL",
    "Como reduzimos em 40% o tempo de análise operacional com IA.",
    "Segmento",
    "Inteligência Artificial",
    "-40% tempo de análise",
    "40%",
    "Redução no tempo de análise",
    "3 meses",
    "Prazo de implementação",
    "100%",
    "Adoção pelo time operacional",
    "O CENÁRIO",
    "O problema que não podia continuar assim.",
    "Uma empresa de médio porte do setor industrial lidava com um processo de análise operacional feito manualmente, por planilhas, com dados chegando com horas de atraso. A equipe de operações gastava até 6 horas por turno consolidando informações que deveriam estar disponíveis em tempo real.",
    "Com dados atrasados, as decisões dependiam de estimativa. Falhas se acumulavam antes de serem identificadas. E o time que deveria estar focado em melhoria contínua estava preso em tarefas repetitivas sem valor estratégico.",
    "A SOLUÇÃO",
    "O que a Orbe Soft fez.",
    "Desenvolvemos um modelo de machine learning treinado com o histórico de dados da operação, integrado diretamente aos sistemas existentes sem exigir substituição de infraestrutura. O modelo passou a classificar automaticamente as ocorrências e gerar alertas preditivos com base em padrões identificados nos dados.",
    "Integração de dados",
    "Conectamos as fontes dispersas em um único pipeline, eliminando a consolidação manual.",
    "Modelo preditivo",
    "Treinamos o modelo com 18 meses de histórico para antecipar falhas com até 4 horas de antecedência.",
    "Painel operacional",
    "Entregamos uma interface simples para que o time de operações visualizasse alertas e tomasse decisões sem depender de TI.",
    "O IMPACTO",
    "O que mudou depois.",
    "Em três meses de operação, o processo que antes consumia horas passou a acontecer de forma automática — com mais precisão e sem depender de ninguém para acionar.",
    "VOZ DO CLIENTE",
    "“A Orbe, que desenvolveu o site do meu instituto, fez um trabalho excelente. Foram muito atenciosos em cada etapa do processo, sempre ouvindo nossas necessidades e entregando um resultado de alta qualidade. Fiquei muito satisfeito e recomendo!”",
    "Lucas Lalla",
    "[cargo], Instituto Vida Para Todos",
    "Seu desafio tem solução.",
    "Se você identificou situações parecidas com o que foi descrito aqui, podemos fazer um diagnóstico para entender onde a tecnologia pode gerar o mesmo tipo de impacto na sua operação.",
    "AGENDAR DIAGNÓSTICO ESTRATÉGICO",
    "CASES",
    "Histórias de impacto real.",
    "INTELIGÊNCIA ARTIFICIAL",
    "Como reduzimos em 40% o tempo de análise operacional com machine learning",
    "LER CASE COMPLETO",
    "VER TODOS OS CASES",
    "Acompanhe nossas redes",
    "Sobre",
    "Home",
    "Quem Somos",
    "Soluções",
    "Cases",
    "Links Rápidos",
    "Contato",
    "Trabalhe Conosco",
    "Termos de Uso",
    "Políticas de Privacidade",
    "Políticas de Cookies",
    "© 2017–2026 - Orbe Soft",
    "Created by",
    "Voltar ao topo"
  ],
  "cases": [
    "LER CASE COMPLETO",
    "Soluções",
    "Cases",
    "Sobre",
    "PT",
    "Falar com especialista",
    "CASES",
    "Cada projeto que entregamos começa com um problema real e termina com impacto mensurável. Aqui estão as histórias de quem confiou na Orbe Soft para transformar operação, produto e decisão em resultado.",
    "Encontre o case mais próximo da realidade da sua operação.",
    "Pesquisar cases",
    "Todas as soluções",
    "Todos os setores",
    "INTELIGÊNCIA ARTIFICIAL",
    "Como reduzimos em 40% o tempo de análise operacional com machine learning",
    "LER CASE COMPLETO",
    "Fábrica de Software",
    "Como modernizamos um sistema legado crítico sem parar a operação",
    "Um sistema central com anos de acumulação técnica travava o crescimento e concentrava risco em uma única estrutura frágil.",
    "LER CASE COMPLETO",
    "UX/UI design",
    "Como aumentamos em 60% a taxa de conclusão de cadastro com redesign de fluxo",
    "O produto funcionava, mas os usuários abandonavam o onboarding antes de completar o cadastro.",
    "LER CASE COMPLETO",
    "Indústria 4.0",
    "Como reduzimos paradas não planejadas em 35% com monitoramento em tempo real",
    "Falhas em equipamentos eram descobertas tarde demais — quando a linha já havia parado.",
    "LER CASE COMPLETO",
    "it Staff Augmentation",
    "Como ampliamos a capacidade de entrega sem aumentar o headcount fixo",
    "O time de produto tinha backlog crescente e não conseguia entregar features críticas no prazo sem comprometer a qualidade.",
    "LER CASE COMPLETO",
    "MANIFESTO",
    "Cases não são portfólio. São evidência.",
    "Telas bonitas qualquer um mostra. O que importa para uma empresa que está decidindo onde investir é saber se o parceiro tecnológico já resolveu um problema parecido com o seu — e se pode provar. Cada case aqui foi construído com um objetivo claro, entregue com método e validado pelo resultado.",
    "VALIDADO POR",
    "Seu desafio pode ser o próximo case.",
    "Se você tem um problema real que precisa de solução tecnológica, podemos começar com um diagnóstico — sem compromisso e com a experiência de quem já fez isso antes.",
    "AGENDAR DIAGNÓSTICO ESTRATÉGICO",
    "Acompanhe nossas redes",
    "Sobre",
    "Home",
    "Quem Somos",
    "Soluções",
    "Cases",
    "Links Rápidos",
    "Contato",
    "Trabalhe Conosco",
    "Termos de Uso",
    "Políticas de Privacidade",
    "Políticas de Cookies",
    "© 2017–2026 - Orbe Soft",
    "Created by",
    "Voltar ao topo"
  ]
};
